### ISSUE TITLE
It doesn't work when downloaded from Elgato Marketplace

### ISSUE THREAD

**Issue by ghost** [distrustME/streamdeck-wakatime#3]
Hi
When I installed your plugin from the [Elgato Marketplace](https://marketplace.elgato.com/product/wakatime-84617dad-df43-4c60-b79a-d23dd2b2775f), I only saw an empty field on a green background
I tried to enter my username, API key and minutes, but nothing happened. So, I downloaded version 1.0.12 from your GitHub releases, and now everything works fine
Could you please update your release on the Elgato Marketplace? The version there is still 1.0.11

**Comment by Morphclue** [comment]
Many thanks for letting me know. I wrote a message to the support-team to include the new version. I will close the ticket as soon as I receive an answer.

**Comment by Morphclue** [comment]
Version 1.0.12 is now on the Marketplace. If you have any further problems, please open a new ticket. I'll see if I can find some time to tweak the plugin in the next few days. **Maybe** there will be another version right away. Thanks again for letting me know!
